# -*- coding: utf-8 -*-
"""suc_W4A16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-L5B4zKtx4ClPOMlgmr_ykOwIASkGeK
"""



"""https://github.com/vllm-project/compressed-tensors

https://huggingface.co/models?search=W4A16

https://github.com/vllm-project/compressed-tensors/tree/main

https://docs.vllm.ai/en/latest/features/quantization/llm_compressor/int4/

https://aistudio.google.com/prompts/1hsBEt7FpMJk_SAsdHVoS0ZH-tFk52xz7
"""

الإجابة باختصار: لا، ليس دائماً، لكن صيغة W4A16 هي الأكثر شيوعاً واستخداماً بنسبة تزيد عن 90%.
أولاً: ماذا تعني الحروف والأرقام؟
في عالم تكميم النماذج (Quantization)، يتم تقسيم البيانات داخل النموذج إلى شقين:
W (Weights - الأوزان): هي أرقام النموذج الثابتة المحفوظة في ملفات الـ SafeTensors (التي قمت بضغطها إلى 4-bit لتقليل استهلاك الـ VRAM).
A (Activations - التنشيطات): هي الإشارات والأرقام التي تنتج لحظياً أثناء مرور السؤال والكلمات عبر طبقات النموذج أثناء التوليد.


خلاصة:
أي نموذج مكتوب عليه INT4 في الغالبية العظمى من الأدوات الشائعة (مثل vLLM, Ollama, GGUF/Q4, GPTQ, AWQ) هو فعلياً W4A16 (أوزان مضغوطة 4-bit لتقليل المساحة، وحسابات تجري بدقة 16-bit للحفاظ على العقل والذكاء).

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# git clone https://github.com/vllm-project/compressed-tensors
# cd compressed-tensors
# pip install -e .

from huggingface_hub import login

# ضع التوكن الخاص بك هنا
HF_TOKEN = "XXXXXXXXXXXXX"
login(token=HF_TOKEN)

cd compressed-tensors

!python /content/compressed-tensors/examples/compress_w4a16.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!git clone https://github.com/vllm-project/vllm.git

####
#
# The following example shows how a model can be quantized and packed
# entirely with primitives within `compressed-tensors`.
# The int4_config.json defines weights-only INT4 quantization,
# so we only need to compute weight scales (no calibration data needed).
# Weights are packed into int32 using the PackedQuantizationCompressor:
# src/compressed_tensors/compressors/pack_quantized/base.py
# Note: This is doing basic quantization. For better accuracy recovery,
# consider using GPTQ throught LLM-Compressor
#
####

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import math
from pathlib import Path

import torch
from compressed_tensors.compressors import ModelCompressor
from compressed_tensors.quantization import (
    QuantizationConfig,
    apply_quantization_config,
)
from compressed_tensors.quantization.utils import calculate_qparams
from transformers import AutoModelForCausalLM


model_name = "Qwen/Qwen3.5-4B"
device = "cuda:0" if torch.cuda.is_available() else "cpu"
# Load the model
model = AutoModelForCausalLM.from_pretrained(
    model_name, device_map=device, torch_dtype="auto"
)



# Set-up the quantization config from a JSON file. This defines:
# 1. What quantization scheme we're applying and to which layers
# 2. Any layers that should be ignored
# In this case, int4_config.json targets all Linear layers with weights-only INT4 quantization.
# All the quantization arguments are described through the QuantizationArgs,
# found in src/compressed_tensors/quantization/quant_args.py

config_file = Path(__file__).parent / "int4_config.json"
config = QuantizationConfig.model_validate_json(config_file.read_text())

# Apply the config to the model. This step uses the config to define
# the quantization parameters (such as the scales) for the targeted layers
# and attaches a QuantizationScheme which defines how the weights and activations
# should be quantized (e.g number of bits, group or block sizes, etc)
apply_quantization_config(model, config)

# Compute weight scales using round-to-nearest quantization
for name, module in model.named_modules():
    # Only target layers with a QuantizationScheme attached
    scheme = getattr(module, "quantization_scheme", None)
    if scheme is None or scheme.weights is None:
        continue

    weight = module.weight.data
    args = scheme.weights
    # Read the group_size defined in the user provided recipe
    # In this case, that is group_size=128 defined in int4_config.json
    group_size = args.group_size

    # Reshape based on the group_size. With group quantization, we apply a scale every
    # group_size number of rows. Reshape to make it easier to identify the min and max values per group.
    if group_size is not None and group_size > 0:
        reshaped = weight.unflatten(
            -1, (math.ceil(weight.shape[-1] / group_size), group_size)
        )
        min_val = reshaped.amin(dim=-1)
        max_val = reshaped.amax(dim=-1)
    else:
        min_val, max_val = torch.aminmax(weight)

    # Calculate the quantization parameters, such as the weight scale, using the min and max values
    scale, _ = calculate_qparams(min_val, max_val, args)
    # Update the parameters attached to the module based on the calculated value
    # In this case, we update the `weight_scale` attached to the targeted linear layers
    module.weight_scale.copy_(scale)

# set-up a compressor
# The compression format is inferred by iterating over all quantized modules and
# checking each format's `can_compress(module_type, scheme)` in priority order
# (see compressed_tensors/compressors/format.py). The format can also be set
# explicitly by passing quantization_format (e.g. quantization_format="pack-quantized")
compressor = ModelCompressor.from_pretrained_model(model)
# Compress the model using the calibrated scales and save it using the pack-quantized format.
# This format defines the weight packing, which can be seamlessly loaded through vLLM.
compressor.compress_model(model)

output_dir = "./Qwen/Qwen3.5-4B-W4A16"
# With pack-quantized, weights are quantized and then packed into int32 tensors
# (e.g. eight 4-bit values per int32). The saved state dict stores weight_packed,
# weight_scale, and weight_shape (replacing the original weight tensor).
model.save_pretrained(output_dir)
# Update the model's config with the relevant compressed-tensors details
compressor.update_config(output_dir)

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from vllm import LLM, SamplingParams

# Sample prompts.
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)


def main():
    # Create an LLM.
    llm = LLM(model="facebook/opt-125m")
    # Generate texts from the prompts.
    # The output is a list of RequestOutput objects
    # that contain the prompt, generated text, and other information.
    outputs = llm.generate(prompts, sampling_params)
    # Print the outputs.
    print("\nGenerated Outputs:\n" + "-" * 60)
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt:    {prompt!r}")
        print(f"Output:    {generated_text!r}")
        print("-" * 60)


if __name__ == "__main__":
    main()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/vllm/examples/basic/offline_inference
!python /content/vllm/examples/basic/offline_inference/basic.py

/content/compressed-tensors/Qwen/Qwen3.5-4B-W4A16

!rm -rf /content/compressed-tensors/Qwen/Qwen3.5-4B-W4A16

import math
import shutil
from pathlib import Path
import torch
from transformers import AutoModelForCausalLM
from compressed_tensors.quantization import QuantizationConfig, apply_quantization_config
from compressed_tensors.quantization.utils import calculate_qparams
from compressed_tensors.compressors import ModelCompressor

# 1. Clean up old checkpoint
output_dir = "./Qwen/Qwen3.5-4B-W4A16"
shutil.rmtree(output_dir, ignore_errors=True)

model_name = "Qwen/Qwen3.5-4B"
device = "cuda:0" if torch.cuda.is_available() else "cpu"

print(f"Loading {model_name}...")
model = AutoModelForCausalLM.from_pretrained(
    model_name, device_map=device, torch_dtype="auto"
)

# 2. Load quantization config and explicitly IGNORE lm_head
config_file = Path("/content/compressed-tensors/examples/int4_config.json")
config = QuantizationConfig.model_validate_json(config_file.read_text())
config.ignore = ["lm_head"]  # <-- CRITICAL: keeps lm_head in unquantized FP16/BF16

apply_quantization_config(model, config)

# 3. Compute weight scales (lm_head is skipped automatically)
print("Computing weight scales...")
for name, module in model.named_modules():
    scheme = getattr(module, "quantization_scheme", None)
    if scheme is None or scheme.weights is None:
        continue

    weight = module.weight.data
    args = scheme.weights
    group_size = args.group_size

    if group_size is not None and group_size > 0:
        reshaped = weight.unflatten(
            -1, (math.ceil(weight.shape[-1] / group_size), group_size)
        )
        min_val = reshaped.amin(dim=-1)
        max_val = reshaped.amax(dim=-1)
    else:
        min_val, max_val = torch.aminmax(weight)

    scale, _ = calculate_qparams(min_val, max_val, args)
    module.weight_scale.copy_(scale)

# 4. Pack and save
print("Packing and saving compressed model...")
compressor = ModelCompressor.from_pretrained_model(model)
compressor.compress_model(model)

model.save_pretrained(output_dir)
compressor.update_config(output_dir)
print(f"Done! Saved to {output_dir}")

!rm -rf /content/vllm/examples/basic/offline_inference/Qwen/Qwen3.5-4B-W4A16

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/vllm/examples/basic/offline_inference

import math
import shutil
from pathlib import Path
import torch
from transformers import AutoModelForCausalLM
from compressed_tensors.quantization import QuantizationConfig, apply_quantization_config
from compressed_tensors.quantization.utils import calculate_qparams
from compressed_tensors.compressors import ModelCompressor

# مسار الحفظ النهائي الموحد
output_dir = "/content/Qwen3.5-4B-W4A16"
shutil.rmtree(output_dir, ignore_errors=True)

model_name = "Qwen/Qwen3.5-4B"
device = "cuda:0" if torch.cuda.is_available() else "cpu"

print(f"1. Loading base model: {model_name}...")
model = AutoModelForCausalLM.from_pretrained(
    model_name, device_map=device, torch_dtype="auto"
)

# قراءة الإعدادات واستثناء lm_head
config_file = Path("/content/compressed-tensors/examples/int4_config.json")
config = QuantizationConfig.model_validate_json(config_file.read_text())
config.ignore = ["lm_head"]  # استثناء lm_head ليقبلها vLLM

apply_quantization_config(model, config)

print("2. Calculating quantization scales...")
for name, module in model.named_modules():
    scheme = getattr(module, "quantization_scheme", None)
    if scheme is None or scheme.weights is None:
        continue

    weight = module.weight.data
    group_size = scheme.weights.group_size

    if group_size is not None and group_size > 0:
        reshaped = weight.unflatten(
            -1, (math.ceil(weight.shape[-1] / group_size), group_size)
        )
        min_val = reshaped.amin(dim=-1)
        max_val = reshaped.amax(dim=-1)
    else:
        min_val, max_val = torch.aminmax(weight)

    scale, _ = calculate_qparams(min_val, max_val, scheme.weights)
    module.weight_scale.copy_(scale)

print("3. Compressing and saving model...")
compressor = ModelCompressor.from_pretrained_model(model)
compressor.compress_model(model)

model.save_pretrained(output_dir)
compressor.update_config(output_dir)
print(f" Compression complete! Saved to {output_dir}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_infer.py
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "Hello, my name is",
#     "The president of the United States is",
#     "The capital of France is",
#     "The future of AI is",
# ]
# 
# sampling_params = SamplingParams(temperature=0.8, top_p=0.95, max_tokens=100)
# 
# def main():
#     llm = LLM(
#         model="/content/Qwen3.5-4B-W4A16",
#         max_model_len=4096,
#         gpu_memory_utilization=0.85,
#         enforce_eager=True,  # لتقليل استهلاك الذاكرة وتفادي مشاكل Inductor/Graph على T4
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text}")
#     print("=" * 50)
# 
# if __name__ == "__main__":
#     main()

from safetensors.torch import load_file

# قراءة ملف الأوزان
weights = load_file("/content/Qwen3.5-4B-W4A16/model.safetensors")

# فحص طبقة عادية (يجب أن تظهر مضغوطة):
print("Backbone layer weight key:", [k for k in weights.keys() if "q_proj" in k][:3])
# ستلاحظ وجود: q_proj.weight_packed, q_proj.weight_scale, q_proj.weight_shape

# فحص طبقة المخرجات (يجب أن تظل unquantized):
assert "lm_head.weight" in weights, "خطأ: lm_head تم ضغطها بالخطأ!"
print("lm_head shape and dtype:", weights["lm_head.weight"].shape, weights["lm_head.weight"].dtype)
print(" تم التحقق الهيكلي بنجاح!")

!pwd

pip install lm-eval

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_infer.py
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "Hello, my name is",
#     "The capital of France is",
#     "The future of artificial intelligence is",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=60,
# )
# 
# def main():
#     print("Loading quantized model with vLLM...")
#     llm = LLM(
#         model="/content/Qwen3.5-4B-W4A16",
#         max_model_len=2048,
#         gpu_memory_utilization=0.85,
#         enforce_eager=True,
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python run_infer.py

import gc
import torch

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()
print("تم تفريغ ذاكرة كارت الشاشة بنجاح!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer.py
# import os
# # إجبار vLLM على العمل بذاكرة نظيفة
# os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
# 
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "Hello, my name is",
#     "The capital of France is",
#     "What is the future of AI?",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=50,
# )
# 
# def main():
#     # تقليل النسبة إلى 0.75 لتترك مساحة كافية على كارت T4
#     llm = LLM(
#         model="/content/Qwen3.5-4B-W4A16",
#         max_model_len=2048,
#         gpu_memory_utilization=0.75,
#         enforce_eager=True,
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python infer.py





"""### aشغال"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/1.py
# import os
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "Hello, my name is",
#     "The capital of France is",
#     "What is the future of AI?",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=60,
# )
# 
# def main():
#     print(">>> Initializing vLLM Engine...")
#     llm = LLM(
#         model="/content/Qwen3.5-4B-W4A16",
#         tokenizer="Qwen/Qwen3.5-4B",  # <-- إضافة هذا السطر لحل المشكلة فوراً
#         max_model_len=2048,
#         gpu_memory_utilization=0.75,
#         enforce_eager=True,
#     )
# 
#     print(">>> Generating outputs...")
#     outputs = llm.generate(prompts, sampling_params)
# 
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python /content/1.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/1.py
# import os
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "Who was Napoleon Bonaparte?",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=128,
# )
# 
# def main():
#     print(">>> Initializing vLLM Engine...")
#     llm = LLM(
#         model="/content/Qwen3.5-4B-W4A16",
#         tokenizer="Qwen/Qwen3.5-4B",  # <-- إضافة هذا السطر لحل المشكلة فوراً
#         max_model_len=2048,
#         gpu_memory_utilization=0.75,
#         enforce_eager=True,
#     )
# 
#     print(">>> Generating outputs...")
#     outputs = llm.generate(prompts, sampling_params)
# 
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python /content/1.py









import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# 1. تحميل الـ Tokenizer
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3.5-4B")

# 2. تحميل النموذج مع تحديد float16 لتجنب حجز مساحات إضافية
model = AutoModelForCausalLM.from_pretrained(
    "/content/Qwen3.5-4B-W4A16",
    device_map="auto",
    dtype=torch.float16,
)

# 3. إعداد قالب المحادثة
messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

# 4. التوليد
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=40,
        temperature=0.7,
        do_sample=True,
    )

# 5. طباعة الرد فقط
response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
print("\nModel Response:\n" + "-" * 30)
print(response)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# 1. تحميل الـ Tokenizer
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3.5-4B")

# 2. تحميل النموذج مع تحديد float16 لتجنب حجز مساحات إضافية
model = AutoModelForCausalLM.from_pretrained(
    "/content/Qwen3.5-4B-W4A16",
    device_map="auto",
    dtype=torch.float16,
)

# 3. إعداد قالب المحادثة
messages = [
    {"role": "user", "content": "what is ai?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

# 4. التوليد
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=40,
        temperature=0.7,
        do_sample=True,
    )

# 5. طباعة الرد فقط
response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
print("\nModel Response:\n" + "-" * 30)
print(response)





AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# 1. تحميل الـ Tokenizer
tokenizer = AutoTokenizer.from_pretrained("AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16")

# 2. تحميل النموذج مع تحديد float16 لتجنب حجز مساحات إضافية
model = AutoModelForCausalLM.from_pretrained(
    "AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16",
    device_map="auto",
    dtype=torch.float16,
)

# 3. إعداد قالب المحادثة
messages = [
    {"role": "user", "content": "what is ai?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

# 4. التوليد
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=40,
        temperature=0.7,
        do_sample=True,
    )

# 5. طباعة الرد فقط
response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
print("\nModel Response:\n" + "-" * 30)
print(response)





from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16")
model = AutoModelForCausalLM.from_pretrained("AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16", device_map="auto")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

import os
os._exit(0)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_8b.py
# from vllm import LLM, SamplingParams
# 
# prompts = [
#     "What is AI?",
#     "Explain quantum computing in simple terms.",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=100,
# )
# 
# def main():
#     print(">>> Loading Llama-3.1-8B-GPTQ-W4A16 into vLLM...")
#     llm = LLM(
#         model="AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16",
#         max_model_len=2048,
#         gpu_memory_utilization=0.85, # سيأخذ حوالي 5.5 جيجابايت فقط للأوزان
#         enforce_eager=True,
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python run_8b.py

max_memory = {0: "12GiB", "cpu": "20GiB"}

model = AutoModelForCausalLM.from_pretrained(
    "AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16",
    device_map="auto",
    max_memory=max_memory,
    dtype=torch.float16,
)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# 1. تحميل الـ Tokenizer
tokenizer = AutoTokenizer.from_pretrained("AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16")

max_memory = {0: "12GiB", "cpu": "20GiB"}

model = AutoModelForCausalLM.from_pretrained(
    "AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16",
    device_map="auto",
    max_memory=max_memory,
    dtype=torch.float16,
)

# 3. إعداد قالب المحادثة
messages = [
    {"role": "user", "content": "what is ai?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

# 4. التوليد
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=40,
        temperature=0.7,
        do_sample=True,
    )

# 5. طباعة الرد فقط
response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
print("\nModel Response:\n" + "-" * 30)
print(response)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_selene.py
# import json
# from pathlib import Path
# from huggingface_hub import snapshot_download
# from vllm import LLM, SamplingParams
# 
# # الحصول على مسار النموذج المحلي المعدل
# model_dir = snapshot_download(repo_id="AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16")
# 
# prompts = [
#     "What is AI?",
#     "Explain the concept of quantum computing simply.",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=80,
# )
# 
# def main():
#     print(">>> Loading patched Llama-3.1-8B into vLLM...")
#     llm = LLM(
#         model=model_dir,
#         max_model_len=2048,
#         gpu_memory_utilization=0.75, # 75% كافية جداً لـ 8B INT4 على T4
#         enforce_eager=True,
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python run_selene.py

"""### aشغال"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_selene_fixed.py
# import os
# import json
# import shutil
# from pathlib import Path
# from huggingface_hub import snapshot_download
# from vllm import LLM, SamplingParams
# 
# # 1. تنزيل النموذج إلى مجلد محلي ثابت خارج كاش الـ Hub
# model_source = "AtlaAI/Selene-1-Mini-Llama-3.1-8B-GPTQ-W4A16"
# target_dir = Path("/content/Selene-8B-Patched")
# 
# if not target_dir.exists():
#     print(">>> 1. Downloading and copying model to independent local directory...")
#     cached_path = snapshot_download(repo_id=model_source)
#     # نسخ المجلد بالكامل مع فك روابط الـ symlinks ليصبح ملفات حقيقية مستقلة
#     shutil.copytree(cached_path, target_dir, symlinks=False)
# 
#     # 2. تعديل config.json وحذف sparsity_config نهائياً
#     config_file = target_dir / "config.json"
#     config_data = json.loads(config_file.read_text())
# 
#     if "quantization_config" in config_data:
#         # إزالة أي ذكر للـ sparsity
#         config_data["quantization_config"].pop("sparsity_config", None)
#         config_data["quantization_config"].pop("sparsity", None)
# 
#     config_file.write_text(json.dumps(config_data, indent=2))
#     print(">>> Successfully patched config.json in local directory!")
# else:
#     print(">>> Using existing patched model directory:", target_dir)
# 
# # 3. إعداد مدخلات الاختبار
# prompts = [
#     "What is AI?",
#     "Explain the concept of quantum computing simply.",
# ]
# 
# sampling_params = SamplingParams(
#     temperature=0.7,
#     top_p=0.9,
#     max_tokens=80,
# )
# 
# def main():
#     print(">>> Loading local patched Llama-3.1-8B into vLLM...")
#     llm = LLM(
#         model=str(target_dir),  # تمرير المجلد المحلي المعدل
#         max_model_len=2048,
#         gpu_memory_utilization=0.75,
#         enforce_eager=True,
#     )
# 
#     outputs = llm.generate(prompts, sampling_params)
#     print("\n" + "=" * 50)
#     for output in outputs:
#         print(f"\nPrompt: {output.prompt}")
#         print(f"Output: {output.outputs[0].text.strip()}")
#     print("\n" + "=" * 50)
# 
# if __name__ == "__main__":
#     main()

!python run_selene_fixed.py

